Upgraded issue templates to use GitHub issue forms
appwrite/sdk-for-svelte pull request #19
Opened 2021-10-01 06:53 UTC by vendz

a pull request for #18

2021-10-03 10:35 UTC, lohanidamodar commented
@vendz  Great work. One more change before we can approve. We have made few changes in the language and also the format of Code of conduct. Please check https://github.com/appwrite/appwrite template and update accordingly.
Thank you.

2021-10-03 10:48 UTC, vendz commented
@lohanidamodar requested changes have been made. 
kindly review it!

2021-10-04 07:52 UTC, lohanidamodar requested changes
Great work @vendz. Small request to make it even better 🚀

2021-10-04 07:52 UTC, lohanidamodar commented on .github/ISSUE_TEMPLATE/bug.yaml
> +      label: "🎲 Svelte SDK version"
Let's also keep Appwrite version here, as it's relevant.

2021-10-04 08:10 UTC, vendz commented
@lohanidamodar changes have been made.
kindly review it!

2021-10-05 07:20 UTC, lohanidamodar requested changes
Few more changes @vendz !

2021-10-05 07:20 UTC, lohanidamodar commented on .github/ISSUE_TEMPLATE/bug.yaml
> +      label: "🎲 appwrite version"
```suggestion
      label: "🎲 Appwrite version"
```

2021-10-05 07:20 UTC, lohanidamodar commented on .github/ISSUE_TEMPLATE/bug.yaml
> +        - Version 0.0.1 (alpha)
The versions should be Appwrite versions.

2021-10-06 07:26 UTC, vendz commented
@lohanidamodar please review and merge.

2021-10-06 11:55 UTC, christyjacob4 approved these changes

2021-10-06 11:56 UTC, merged

2021-10-06 11:56 UTC, christyjacob4 commented
THANK YOU so much! All changes merged 🥳
Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swag!